export const data = [
  {
    name: 'Islam Alghoul',
    Specialization: 'Software Developer',
    image: './assets/islam.jpg',
    linkedIn: '#',
    github: '#',
    facebook: '#',
  },
  {
    name: 'Alaa Abualadoos',
    Specialization: 'Software Developer',
    image: './assets/alaa.jpg',
    linkedIn: '#',
    github: '#',
    facebook: '#',
  },
  {
    name: 'Bayan Bushnaq',
    Specialization: 'Software Developer',
    image: './assets/bayan.jpg',
    linkedIn: '#',
    github: '#',
    facebook: '#',
  },
  {
    name: 'Mohammad Alfayoume',
    Specialization: 'Software Developer',
    image: './assets/mohammad.jpg',
    linkedIn: '#',
    github: '#',
    facebook: '#',
  },
  {
    name: 'Abdelrahman Alasal',
    Specialization: 'CEO RecruitlQ',
    image: './assets/abed.jpg',
    linkedIn: '#',
    github: '#',
    facebook: '#',
  },
]
