export const data = [
  {
    name: 'Islam Alghoul',
    Specialization: 'Software Developer',
    image: require('./assets/islam.jpg'),
    linkedIn: '#',
    github: '#',
    facebook: '#',
  },
  {
    name: 'Alaa Abualadoos',
    Specialization: 'Software Developer',
    image: require('./assets/alaa.png'),
    linkedIn: '#',
    github: '#',
    facebook: '#',
  },
  {
    name: 'Bayan Bushnaq',
    Specialization: 'Software Developer',
    image: require('./assets/bayan.jpg'),
    linkedIn: '#',
    github: '#',
    facebook: '#',
  },
  {
    name: 'Mohammad Alfayoume',
    Specialization: 'Software Developer',
    image: require('./assets/moh.jpg'),
    linkedIn: '#',
    github: '#',
    facebook: '#',
  },
  {
    name: 'Abdelrahman Alasal',
    Specialization: 'CEO RecruitlQ',
    image: require('./assets/abd.jpg'),
    linkedIn: '#',
    github: '#',
    facebook: '#',
  },
]
